spring:
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  datasource:
    url: jdbc:mysql://company_service_mySQL:3306/company
    username: root
    password: root
    
management:
  endpoint:
    health:
      show-details: always 

server:
   port: 8081
   
xParam: 705  

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-service:8761/eureka/