spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  datasource:
    url: jdbc:mysql://localhost:3306/workshopdb
    username: root
    password: root
    
management:
  endpoint:
    health:
      show-details: always 

server:
   port: 8081
   
xParam: 705  

