spring:
  data:
    mongodb:
      database: Products
      host: mongo
      port: 27017
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://register-service:8761/eureka/  

server:
  port: 8084      